CC = g++
CFLAGS  = -g -Wall
TARGET=CSE_165_QUESTION_1
TARGET1=CSE_165_QUESTION_2
TARGET2=CSE_165_QUESTION_3
TARGET4=CSE_165_QUESTION_4
TARGET5=CSE_165_QUESTION_5

Array:
	$(CC) CSE_165_QUESTION_3.cpp StackofInt.cpp StackImpArray.cpp -o $(TARGET2)  

Vector:
	$(CC) CSE_165_QUESTION_3.cpp StackofInt.cpp StackImpVector.cpp -o $(TARGET2) 
	
		
clean:
	rm -f $(TARGET2)  StackofInt StackImpArray StackImpVector

run3:
	./CSE_165_QUESTION_3


